apiVersion: v1
data:
  ingress: |-
    {
      "ingressGateway" : "knative-ingress-gateway.knative-serving",
      "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
      "localGateway": "cluster-local-gateway.knative-serving",
      "localGatewayService" : "cluster-local-gateway.istio-system.svc.cluster.local"
    }
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kubeflow