apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-notebook-ci
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeflow-notebook-ci
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - kubeflow.org
    resources:
      - profiles
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - delete
  - apiGroups:
      - kubeflow.org
    resources:
      - notebooks
    verbs:
      - get
      - list
      - patch
  - verbs:
      - get
      - list
      - create
      - delete
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - pods/exec
      - pods/attach
      - pods/log
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeflow-notebook-ci
roleRef:
  kind: ClusterRole
  name: kubeflow-notebook-ci
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kubeflow-notebook-ci

