apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-api-auth
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeflow-api-auth
rules:
  - apiGroups:
      - kubeflow.org
      - serving.kubeflow.org
    resources:
      - notebooks
      - inferenceservices
      - profiles
    verbs: 
      - get
      - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeflow-api-auth
roleRef:
  kind: ClusterRole
  name: kubeflow-api-auth
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kubeflow-api-auth
